[package]
name = "eta-algorithms"
version = "1.2.2"
edition = "2021"
authors = ["erik9631@gmail.com"]
description = "Low overhead data structures focused on performance"
license = "MIT"

[profile.test]
debug = true
inherits = "release"